//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class airplanedestination
    {
        public int weeknumber { get; set; }
        public Nullable<int> todestination { get; set; }
        public Nullable<int> fromdestination { get; set; }
        public string destination { get; set; }
    
        public virtual destination destination1 { get; set; }
    }
}
