//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public Nullable<int> numberofpeople { get; set; }
        public Nullable<int> startweek { get; set; }
        public Nullable<int> price { get; set; }
        public string costumer { get; set; }
        public Nullable<int> vacationhouse { get; set; }
    
        public virtual costumer costumer1 { get; set; }
        public virtual vacationhouse vacationhouse1 { get; set; }
    }
}
