//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class destination
    {
        public destination()
        {
            this.airplanedestinations = new HashSet<airplanedestination>();
            this.vacationhouses = new HashSet<vacationhouse>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string dayofchange { get; set; }
        public Nullable<int> priceprperson { get; set; }
    
        public virtual ICollection<airplanedestination> airplanedestinations { get; set; }
        public virtual ICollection<vacationhouse> vacationhouses { get; set; }
    }
}
