//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacationweek
    {
        public int weeknumber { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> isBooked { get; set; }
        public int vacationhouseid { get; set; }
    
        public virtual vacationhouse vacationhouse { get; set; }
    }
}
